- name: Uninstall RabbitMQ in Master
  hosts: localhost
  become: yes
  become_method: sudo
  tasks:
     - name: Autoremove for RabbitMQ in Master
       shell: apt autoremove -y --purge rabbitmq-server

#master-slave ayarlaması erlang.cookie to same localhost in slave
- name: Uninstall RabbitMQ in Slave
  hosts: 10.115.207.250
  become: yes
  become_method: sudo
  tasks:
     - name: Autoremove for RabbitMQ in Slave
       shell: apt autoremove -y --purge rabbitmq-server
